.IX Title "magnetic 8"
.TH geographiclib-get-magnetic 8 "" "GeographicLib" "GeographicLib"
.SH "NAME"
geographiclib-get-magnetic \-\- a GeographicLib administrative tool
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\&\fBgeographiclib-get-magnetic\fR downloads and installs the magnetic datasets used by
GeographicLib, <http://geographiclib.sf.net>.  For documentation, supply
the \fB-h\fR option:
.PP
.Vb 2
\&   geographiclib-get-magnetic -h
.Ve
.PP
By default, the datasets are installed in
\&\f(CW\*(C`/home/abdelrahman/Arduino/imu task/Testing workspace/devel/share/geographic_lib/data/magnetic\*(C'\fR and
the script requires write access to this directory.
